//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class hakkimizda
    {
        public int id { get; set; }
        public string foto { get; set; }
        public virtual HttpPostedFileBase fotoFile { get; set; }
        public string baslik { get; set; }
        public string ustbaslik { get; set; }
        public string icerik { get; set; }
        public Nullable<bool> aktif { get; set; }
        public Nullable<int> sira { get; set; }
    }
}
