//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class site2020Entities : DbContext
    {
        public site2020Entities()
            : base("name=site2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<anasayfa> anasayfa { get; set; }
        public DbSet<hakkimizda> hakkimizda { get; set; }
        public DbSet<iletisim> iletisim { get; set; }
        public DbSet<kullanicilar> kullanicilar { get; set; }
        public DbSet<urunler> urunler { get; set; }
    }
}
