//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class urunler
    {
        public int id { get; set; }
        public string foto { get; set; }
        public virtual HttpPostedFileBase fotoFile { get; set; }

        [Required]
        [Display(Name = "Başlık")]
        public string baslik { get; set; }

        [Required]
        [Display(Name = "Üst Başlık")]
        public string ustbaslik { get; set; }

        [Required]
        [Display(Name = "Üst Başlık")]
        [AllowHtml]
        public string icerik { get; set; }

        public bool aktif { get; set; }

        [Required]
        [Display(Name = "Sıra")]
        public Nullable<int> sira { get; set; }
    }
}
